version: "3.9"
services:
  tor:
    env_file:
      - fileName
    build:
      context: .
      args:
        TOR_NICKNAME: nickname
        TOR_ORPORT: 9001
        TOR_ADDRESS: ip
        TOR_BANDWITH: 5MBytes
        TOR_BANDWITH_BURST: 10MBytes
        TOR_CONTACT: "contact information"
    image: torpine:latest
    container_name: torpine
    ports:
      - "9001:9001"    

    networks:
      - torpine

networks:
  torpine: